[build]
  # Path where the Next.js project is located
  base    = "heray-app"
  # Command Netlify should run to build the project
  command = "npm run build"
  # Directory to publish (Next.js output)
  publish = ".next"

[functions]
  # Netlify will output Next.js API routes / middleware here
  directory = ".netlify/functions"

[[plugins]]
  # Official Netlify plugin to enable Next.js runtime features
  package = "@netlify/next" 