import type { Metadata } from "next";
import { GeistSans as GeistSansFont } from "geist/font/sans";
import { GeistMono as GeistMonoFont } from "geist/font/mono";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSansFont.variable} ${GeistMonoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
